### ISSUE TITLE
invalid syntax on python 3.8

### ISSUE THREAD

**Issue by CoffeeIsLife87** [CorporalQuesadilla/Steam-Shortcut-Manager#5]
![InkedAnnotation 2020-03-18 095450_LI](https://user-images.githubusercontent.com/36961653/76974064-bc65ee00-68fe-11ea-8adb-1f25394a5a15.jpg)
The file has not been changed since downloading

**Comment by t0mtee** [comment]
@herosilas12 How did you fix this (if you did) Python 2.7.18 is giving me an error

**Comment by CoffeeIsLife87** [comment]
put brackets around 

```
geturl(inputTuple)
```
so that it looks like

```
(geturl(inputTuple))
 ```
also I made a tool using this so if you want to add a lot of shortcuts you should check out https://github.com/herosilas12/Batch-steam-shortcut-creator
